### ISSUE TITLE
pg_dump: error: query failed: ERROR:  permission denied for table topology

### ISSUE THREAD

**Issue by organicnz** [mansueli/Supa-Migrate#3]
Hi mate,

Apologies. Could you pls help with this one? I assume it's caused by the extension POSTGIS_TOPOLOGY. Do I need to change the privileges for the table `topology` at this point? :)

```
sudo sh backup_database.sh
pg_dump: error: query failed: ERROR:  permission denied for table topology
pg_dump: error: query was: COPY "topology"."topology" ("id", "name", "srid", "precision", "hasz") TO stdout;
```

Thank you :)

**Comment by mansueli** [comment]
It sounds like this is an extension on the PostGIS schema. 

Could you try the following:

Include this table in the dump script:
`  --exclude-table 'topology.topology' \`

Above
`  --exclude-table-data 'storage.objects' \`

Then, you should be able to restore by enabling the PostGIS extension directly in Supabase before importing:
https://app.supabase.com/project/_/database/extensions

Let me know if you run into further issues.

**Comment by organicnz** [comment]
Thanks mate. Yeah, the exclusion has resolved the issue with `topology` :)

Probably I should exclude the `layer` table in the same way :)

```
sudo sh backup_database.sh
pg_dump: error: query failed: ERROR:  permission denied for table layer
pg_dump: error: query was: COPY "topology"."layer" ("topology_id", "layer_id", "schema_name", "table_name", "feature_column", "feature_type", "level", "child_id") TO stdout;
```

**Comment by organicnz** [comment]
Nice, the second exclusion has helped as well :) 

` --exclude-table 'topology.layer' \` 

```
organic@organics-MacBook-Pro Supa-Migrate % ls -la
total 29160
drwxr-xr-x   9 organic  staff       288 Feb 17 15:20 .
drwxr-xr-x  10 organic  staff       320 Feb  8 00:36 ..
drwxr-xr-x  10 organic  staff       320 Feb  5 10:26 .config
drwxr-xr-x  13 organic  staff       416 Feb  9 09:54 .git
-rw-r--r--   1 organic  staff   1980637 Feb  5 10:26 backup.zip
-rw-r--r--   1 organic  staff      1203 Feb 17 15:20 backup_database.sh
-rw-r--r--   1 organic  staff  12940334 Feb 17 15:20 dump.sql
-rw-r--r--   1 organic  staff         0 Feb  5 10:26 log
drwxr-xr-x   8 organic  staff       256 Feb  5 10:26 sample_data

```

**Comment by mansueli** [comment]
PS: you can use wildcard there:

`--exclude-table 'topology.*' \`

Not familiar with PostGIS, I assumed it was one faulty table.

**Comment by organicnz** [comment]
Ohh, right. Nice one. Thanks so much for the quick help :)

Maybe I got something mixed up lol :))
