### ISSUE TITLE
[Migrate everything script] pg_dump: error: options -c/--clean and -a/--data-only cannot be used together

### ISSUE THREAD

**Issue by StacySiz** [mansueli/Supa-Migrate#8]
Hi! 

I'm trying to run "Migrate everything script" against my stage db
I edited old/new supabase URLs in the beginning of the script, applied chmod and run it

It gave me the following errors:

```
./stage-migration.sh: line 21: --exclude-schema: command not found
pg_dump: error: options -c/--clean and -a/--data-only cannot be used together
./stage-migration.sh: line 30: --exclude-schema: command not found
```

**Comment by mansueli** [comment]
Hey @StacySiz, are you migrating between Supabase projects?

I'll test this later today and update if I find an issue. Also, are you running from MacOS/ Linux/ Windows?

**Comment by StacySiz** [comment]
Hi @mansueli , thanks for the prompt reply!

Yes, between Supabase projects, my goal is to change regions 

I'm running MacOS
Just as in the [guide's reference link](https://stackoverflow.com/questions/44654216/correct-way-to-install-psql-without-full-postgres-on-macos/55564878#55564878) I run libpq and export path commands

**Comment by lerayj** [comment]
@StacySiz as mentioned in the error, having  `--clean` and `--data-only` does not make sense since `--clean` only plays a role in the schema.

From the [Postgres doc](https://www.postgresql.org/docs/current/app-pgdump.html)
> -c --clean
Output commands to DROP all the dumped database objects prior to outputting the commands for creating them. This option is useful when the restore is to overwrite an existing database. If any of the objects do not exist in the destination database, ignorable error messages will be reported during restore, unless --if-exists is also specified.

This option is ignored when emitting an archive (non-text) output file. For the archive formats, you can specify the option when you call pg_restore.

You will probably have another typo where multi-line separator are missing on  `--schema-only` and  `--data-only`
I tweaked it as follows and it's working.

```
#!/usr/bin/env bash

#Edit here:
SUPAVISOR_URL=<YOUR CONNEC STRING>

#Script:
# Default case for Linux sed, just use "-i"
sedi=(-i)
case "$(uname)" in
  # For macOS, use two parameters
  Darwin*) sedi=(-i "")
esac

pg_dump "$SUPAVISOR_URL" \
  --clean \
  --if-exists \
  --quote-all-identifiers \
  --exclude-table-data 'storage.objects' \
  --schema-only \
  --exclude-schema 'extensions|graphql|graphql_public|net|tiger|pgbouncer|vault|realtime|supabase_functions|storage|pg*|information_schema' \
  --schema '*' > dump.sql

pg_dump "$SUPAVISOR_URL" \
  --quote-all-identifiers \
  --exclude-table-data 'storage.objects' \
  --data-only \
  --exclude-schema 'extensions|graphql|graphql_public|net|tiger|pgbouncer|vault|realtime|supabase_functions|storage|pg*|information_schema' \
  --schema '*' > data_dump.sql

sed "${sedi[@]}" -e 's/^DROP SCHEMA IF EXISTS "auth";$/-- DROP SCHEMA IF EXISTS "auth";/' dump.sql
sed "${sedi[@]}" -e's/^DROP SCHEMA IF EXISTS "storage";$/-- DROP SCHEMA IF EXISTS "storage";/' dump.sql
sed "${sedi[@]}" -e 's/^CREATE SCHEMA "auth";$/-- CREATE SCHEMA "auth";/' dump.sql
sed "${sedi[@]}" -e 's/^CREATE SCHEMA "storage";$/-- CREATE SCHEMA "storage";/' dump.sql
sed "${sedi[@]}" -e 's/^ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin"/-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin"/' dump.sql
```
However, I don't understand why @mansueli does not use `-Fc` to have a custom export and be able to use `pg_restore`. With this plain text dump, you are stuck with `psql` only. Maybe because the sed added is then impossible to add ?
I don't understand either why making 2 different dumps and not a global one.

**Comment by lerayj** [comment]
Btw, I'm pretty sure that we should add `--disable-triggers` to the script. In this situation, trigger during the restore process (can't confirm 100%). That also a reason why it would be safer to have pg_restore, that allow to pilot this at restore time, and not at the dump time.

**Comment by StacySiz** [comment]
@lerayj @mansueli 

Yes, seems that the "Migrate everything" script in this repository (https://github.com/mansueli/Supa-Migrate) appears to be outdated and non-functional. Could you kindly update it to a working version?
(script from above comment has SUPAVISOR_URL but not Old, New DB urls as script "Migrate everything")

Additionally, I'm planning to use the "Migrate storage" (Migrating Objects) script soon. It would be great to confirm its functionality as well before I proceed.

Thank you for your attention to these matters!

**Comment by mansueli** [comment]
> However, I don't understand why @mansueli does not use -Fc to have a custom export and be able to use pg_restore. With this plain text dump, you are stuck with psql only. Maybe because the sed added is then impossible to add ?

I've faced several issues with multifile restore and prefer avoiding it unless the DB is over 100GB. 

>I don't understand either why making 2 different dumps and not a global one

Splitting the backup into schema & data speeds up the process to about a third of the time it takes for a single full backup that doesn't use `/copy`.

----

> Yes, seems that the "Migrate everything" script in this repository (https://github.com/mansueli/Supa-Migrate) appears to be outdated and non-functional. Could you kindly update it to a working version?
(script from above comment has SUPAVISOR_URL but not Old, New DB urls as script "Migrate everything")

I've tested `migrate everything` here on my macOs. Just make sure you enable the extensions before running the migration (if you had any enabled in the older/previous project)

>Additionally, I'm planning to use the "Migrate storage" (Migrating Objects) script soon. It would be great to confirm its functionality as well before I proceed.

I've updated & tested with the latest version of Supabase-py. Let me know if you face any issues.
